/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 18:22:56 GMT 2018
 */

package org.telegram.telegrambots.facilities;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.bots.DefaultBotOptions;
import org.telegram.telegrambots.facilities.TelegramHttpClientBuilder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TelegramHttpClientBuilder_ESTest extends TelegramHttpClientBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        TelegramHttpClientBuilder.build((DefaultBotOptions) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.facilities.TelegramHttpClientBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultBotOptions defaultBotOptions0 = new DefaultBotOptions();
      DefaultBotOptions.ProxyType defaultBotOptions_ProxyType0 = DefaultBotOptions.ProxyType.SOCKS5;
      defaultBotOptions0.setProxyType(defaultBotOptions_ProxyType0);
      // Undeclared exception!
      try { 
        TelegramHttpClientBuilder.build(defaultBotOptions0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.telegram.telegrambots.facilities.proxysocketfactorys.SocksSSLConnectionSocketFactory
         //
         verifyException("org.telegram.telegrambots.facilities.TelegramHttpClientBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultBotOptions defaultBotOptions0 = new DefaultBotOptions();
      DefaultBotOptions.ProxyType defaultBotOptions_ProxyType0 = DefaultBotOptions.ProxyType.HTTP;
      defaultBotOptions0.setProxyType(defaultBotOptions_ProxyType0);
      // Undeclared exception!
      try { 
        TelegramHttpClientBuilder.build(defaultBotOptions0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org.apache.http.conn.ssl.SSLConnectionSocketFactory
         //
         verifyException("org.telegram.telegrambots.facilities.TelegramHttpClientBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultBotOptions.ProxyType defaultBotOptions_ProxyType0 = DefaultBotOptions.ProxyType.SOCKS4;
      DefaultBotOptions defaultBotOptions0 = new DefaultBotOptions();
      defaultBotOptions0.setProxyType(defaultBotOptions_ProxyType0);
      // Undeclared exception!
      try { 
        TelegramHttpClientBuilder.build(defaultBotOptions0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.telegram.telegrambots.facilities.proxysocketfactorys.SocksSSLConnectionSocketFactory
         //
         verifyException("org.telegram.telegrambots.facilities.TelegramHttpClientBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultBotOptions defaultBotOptions0 = new DefaultBotOptions();
      // Undeclared exception!
      TelegramHttpClientBuilder.build(defaultBotOptions0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TelegramHttpClientBuilder telegramHttpClientBuilder0 = new TelegramHttpClientBuilder();
  }
}
