/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 18:49:47 GMT 2018
 */

package org.telegram.abilitybots.api.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.abilitybots.api.util.AbilityMessageCodes;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbilityMessageCodes_ESTest extends AbilityMessageCodes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AbilityMessageCodes abilityMessageCodes0 = new AbilityMessageCodes();
  }
}
