/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Oct 22 18:22:56 GMT 2018
 */

package org.telegram.telegrambots.facilities;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TelegramHttpClientBuilder_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.telegram.telegrambots.facilities.TelegramHttpClientBuilder"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/felipe/eclipse-workspace/TelegramBots/telegrambots"); 
    java.lang.System.setProperty("user.home", "/home/felipe"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "felipe"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TelegramHttpClientBuilder_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.http.io.HttpMessageParserFactory",
      "org.apache.http.config.SocketConfig",
      "org.apache.http.client.config.RequestConfig",
      "org.apache.http.StatusLine",
      "org.apache.http.impl.DefaultBHttpClientConnection",
      "org.apache.http.config.Registry",
      "org.apache.http.cookie.MalformedCookieException",
      "org.apache.http.io.SessionOutputBuffer",
      "org.apache.http.RequestLine",
      "org.apache.http.conn.ConnectionRequest",
      "org.apache.http.config.Lookup",
      "org.apache.http.config.SocketConfig$Builder",
      "org.apache.http.HttpMessage",
      "org.apache.http.HttpRequestInterceptor",
      "org.apache.http.client.AuthCache",
      "org.apache.http.HeaderIterator",
      "org.apache.http.conn.ClientConnectionManager",
      "org.apache.http.TruncatedChunkException",
      "org.apache.http.conn.scheme.SchemeSocketFactory",
      "org.telegram.telegrambots.bots.DefaultBotOptions$ProxyType",
      "org.apache.http.HttpInetConnection",
      "org.apache.http.conn.HttpClientConnectionManager",
      "org.apache.http.HttpRequest",
      "org.apache.http.client.BackoffManager",
      "org.apache.http.HttpException",
      "org.apache.http.cookie.CookieSpec",
      "org.apache.http.client.AuthenticationStrategy",
      "org.apache.http.conn.ssl.AllowAllHostnameVerifier",
      "org.apache.http.conn.socket.ConnectionSocketFactory",
      "org.apache.http.client.CredentialsProvider",
      "org.apache.http.conn.util.PublicSuffixMatcher",
      "org.apache.http.conn.routing.RouteInfo$LayerType",
      "org.telegram.telegrambots.updatesreceivers.ExponentialBackOff",
      "org.apache.http.client.ClientProtocolException",
      "org.apache.http.client.methods.Configurable",
      "org.apache.http.config.RegistryBuilder",
      "org.telegram.telegrambots.facilities.proxysocketfactorys.SocksSSLConnectionSocketFactory",
      "org.apache.http.impl.io.EmptyInputStream",
      "org.apache.http.io.HttpTransportMetrics",
      "org.apache.http.client.methods.HttpUriRequest",
      "org.apache.http.protocol.HttpRequestExecutor",
      "org.apache.http.client.methods.HttpRequestWrapper",
      "org.apache.http.io.SessionInputBuffer",
      "org.apache.http.conn.util.PublicSuffixList",
      "org.apache.http.conn.ssl.AbstractVerifier",
      "org.apache.http.conn.ConnectTimeoutException",
      "org.apache.http.impl.io.ContentLengthInputStream",
      "org.apache.http.client.HttpClient",
      "org.apache.http.auth.Credentials",
      "org.apache.http.cookie.Cookie",
      "org.apache.http.io.HttpMessageParser",
      "org.apache.http.impl.BHttpConnectionBase",
      "org.apache.http.HttpConnectionMetrics",
      "org.apache.http.io.HttpMessageWriter",
      "org.apache.http.HttpClientConnection",
      "org.apache.http.conn.ConnectionPoolTimeoutException",
      "org.telegram.telegrambots.meta.generics.BotOptions",
      "org.apache.http.protocol.HttpProcessor",
      "org.apache.http.protocol.HttpCoreContext",
      "org.apache.http.client.methods.HttpRequestWrapper$HttpEntityEnclosingRequestWrapper",
      "org.apache.http.auth.AuthProtocolState",
      "org.apache.http.client.RedirectStrategy",
      "org.apache.http.ProtocolVersion",
      "org.apache.http.impl.io.ChunkedInputStream",
      "org.apache.http.protocol.HttpContext",
      "org.apache.http.auth.AuthScope",
      "org.apache.http.params.HttpParams",
      "org.apache.http.HttpResponse",
      "com.google.common.base.Preconditions",
      "org.apache.http.impl.client.HttpClientBuilder",
      "org.apache.http.HttpHost",
      "org.apache.http.conn.UnsupportedSchemeException",
      "org.apache.http.ProtocolException",
      "org.apache.http.MalformedChunkCodingException",
      "org.apache.http.client.protocol.HttpClientContext",
      "org.apache.http.config.MessageConstraints",
      "org.apache.http.Header",
      "org.telegram.telegrambots.facilities.proxysocketfactorys.HttpSSLConnectionSocketFactory",
      "org.apache.http.io.HttpMessageWriterFactory",
      "org.apache.http.conn.ConnectionKeepAliveStrategy",
      "org.apache.http.concurrent.Cancellable",
      "org.apache.http.conn.ssl.X509HostnameVerifier",
      "org.apache.http.impl.io.ContentLengthOutputStream",
      "org.apache.http.entity.ContentLengthStrategy",
      "org.apache.http.conn.routing.HttpRoutePlanner",
      "org.apache.http.conn.ssl.NoopHostnameVerifier",
      "org.apache.http.Consts",
      "org.apache.http.conn.ssl.SSLConnectionSocketFactory",
      "org.apache.http.util.ByteArrayBuffer",
      "org.telegram.telegrambots.facilities.TelegramHttpClientBuilder$1",
      "org.apache.http.conn.ssl.SSLInitializationException",
      "org.apache.http.cookie.CookieOrigin",
      "org.apache.http.util.Args",
      "org.apache.http.conn.util.PublicSuffixListParser",
      "org.apache.http.HttpEntity",
      "org.apache.http.conn.util.PublicSuffixMatcherLoader",
      "org.apache.http.config.ConnectionConfig",
      "org.apache.http.conn.socket.LayeredConnectionSocketFactory",
      "org.apache.http.conn.scheme.Scheme",
      "org.apache.http.HttpResponseInterceptor",
      "org.apache.http.util.TextUtils",
      "org.apache.http.protocol.BasicHttpContext",
      "org.apache.http.config.MessageConstraints$Builder",
      "org.telegram.telegrambots.facilities.TelegramHttpClientBuilder",
      "org.apache.http.conn.scheme.SocketFactory",
      "org.apache.http.client.config.RequestConfig$Builder",
      "org.apache.http.auth.AuthState",
      "org.apache.http.auth.AuthenticationException",
      "org.apache.http.NameValuePair",
      "org.apache.http.impl.execchain.ClientExecChain",
      "org.apache.http.HttpVersion",
      "org.apache.http.config.ConnectionConfig$Builder",
      "org.apache.http.conn.SchemePortResolver",
      "org.apache.http.impl.io.IdentityInputStream",
      "org.apache.http.conn.DnsResolver",
      "org.telegram.telegrambots.updatesreceivers.ExponentialBackOff$Builder",
      "org.apache.http.conn.ClientConnectionRequest",
      "org.telegram.telegrambots.bots.DefaultBotOptions",
      "org.apache.http.conn.routing.HttpRoute",
      "org.apache.http.client.CookieStore",
      "org.apache.http.client.methods.CloseableHttpResponse",
      "org.apache.http.conn.socket.PlainConnectionSocketFactory",
      "org.apache.http.impl.io.IdentityOutputStream",
      "org.apache.http.auth.AuthScheme",
      "org.apache.http.message.AbstractHttpMessage",
      "org.apache.http.client.HttpRequestRetryHandler",
      "org.apache.http.auth.MalformedChallengeException",
      "org.apache.http.HttpEntityEnclosingRequest",
      "org.apache.http.conn.scheme.SchemeRegistry",
      "org.apache.http.impl.client.CloseableHttpClient",
      "org.apache.http.ParseException",
      "org.apache.http.conn.routing.RouteInfo$TunnelType",
      "org.telegram.telegrambots.facilities.proxysocketfactorys.HttpConnectionSocketFactory",
      "org.apache.http.client.ServiceUnavailableRetryStrategy",
      "org.apache.http.impl.client.InternalHttpClient",
      "org.apache.http.client.methods.HttpExecutionAware",
      "org.apache.http.HeaderElement",
      "org.apache.http.client.UserTokenHandler",
      "org.apache.http.conn.ManagedClientConnection",
      "org.apache.http.client.ConnectionBackoffStrategy",
      "org.apache.http.conn.HttpRoutedConnection",
      "org.apache.http.util.CharArrayBuffer",
      "org.apache.http.impl.io.ChunkedOutputStream",
      "org.apache.http.ConnectionReuseStrategy",
      "org.apache.http.conn.util.DomainType",
      "org.apache.http.ConnectionClosedException",
      "org.apache.http.conn.ConnectionReleaseTrigger",
      "org.apache.http.conn.routing.RouteInfo",
      "org.apache.http.HttpConnection",
      "org.apache.http.client.ResponseHandler",
      "org.apache.http.conn.ManagedHttpClientConnection",
      "org.telegram.telegrambots.facilities.proxysocketfactorys.SocksConnectionSocketFactory"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TelegramHttpClientBuilder_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.telegram.telegrambots.facilities.TelegramHttpClientBuilder",
      "org.telegram.telegrambots.bots.DefaultBotOptions$ProxyType",
      "org.telegram.telegrambots.facilities.TelegramHttpClientBuilder$1",
      "org.telegram.telegrambots.bots.DefaultBotOptions",
      "org.apache.http.protocol.HttpCoreContext",
      "org.apache.http.client.protocol.HttpClientContext",
      "org.apache.http.protocol.BasicHttpContext",
      "org.apache.http.impl.client.HttpClientBuilder",
      "org.apache.http.conn.ssl.NoopHostnameVerifier",
      "org.apache.http.client.config.RequestConfig$Builder",
      "org.apache.http.client.config.RequestConfig",
      "org.apache.http.conn.util.PublicSuffixMatcherLoader",
      "org.apache.http.util.Args",
      "org.apache.http.conn.util.PublicSuffixListParser",
      "org.apache.http.Consts",
      "org.apache.http.conn.util.DomainType",
      "org.apache.http.config.RegistryBuilder",
      "org.apache.http.conn.socket.PlainConnectionSocketFactory",
      "org.telegram.telegrambots.facilities.proxysocketfactorys.SocksConnectionSocketFactory",
      "org.apache.http.util.TextUtils",
      "org.apache.http.conn.ssl.AbstractVerifier",
      "org.apache.http.conn.ssl.AllowAllHostnameVerifier",
      "org.apache.http.conn.ssl.SSLConnectionSocketFactory",
      "org.telegram.telegrambots.updatesreceivers.ExponentialBackOff",
      "org.telegram.telegrambots.updatesreceivers.ExponentialBackOff$Builder",
      "com.google.common.base.Preconditions",
      "org.telegram.telegrambots.facilities.proxysocketfactorys.HttpConnectionSocketFactory",
      "org.apache.http.HttpHost",
      "org.apache.http.impl.BHttpConnectionBase",
      "org.apache.http.impl.DefaultBHttpClientConnection"
    );
  }
}
