/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 18:27:32 GMT 2018
 */

package org.telegram.telegrambots;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.Constants;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Constants_ESTest extends Constants_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Constants constants0 = new Constants();
      assertEquals(75000, Constants.SOCKET_TIMEOUT);
  }
}
