/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 18:20:43 GMT 2018
 */

package org.telegram.telegrambots.updatesreceivers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.security.InvalidParameterException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.bots.DefaultBotOptions;
import org.telegram.telegrambots.meta.generics.BotOptions;
import org.telegram.telegrambots.test.Fakes.FakeLongPollingBot;
import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultBotSession_ESTest extends DefaultBotSession_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      FakeLongPollingBot fakeLongPollingBot0 = new FakeLongPollingBot();
      BotOptions botOptions0 = fakeLongPollingBot0.getOptions();
      defaultBotSession0.setOptions(botOptions0);
      defaultBotSession0.setCallback(fakeLongPollingBot0);
      // Undeclared exception!
      defaultBotSession0.start();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      DefaultBotOptions defaultBotOptions0 = new DefaultBotOptions();
      DefaultBotOptions.ProxyType defaultBotOptions_ProxyType0 = DefaultBotOptions.ProxyType.HTTP;
      defaultBotOptions0.setProxyType(defaultBotOptions_ProxyType0);
      defaultBotSession0.setOptions(defaultBotOptions0);
      FakeLongPollingBot fakeLongPollingBot0 = new FakeLongPollingBot();
      defaultBotSession0.setCallback(fakeLongPollingBot0);
      // Undeclared exception!
      try { 
        defaultBotSession0.start();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.telegram.telegrambots.facilities.proxysocketfactorys.HttpSSLConnectionSocketFactory
         //
         verifyException("org.telegram.telegrambots.facilities.TelegramHttpClientBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      FakeLongPollingBot fakeLongPollingBot0 = new FakeLongPollingBot();
      defaultBotSession0.setCallback(fakeLongPollingBot0);
      // Undeclared exception!
      try { 
        defaultBotSession0.setCallback(fakeLongPollingBot0);
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // Callback has already been set
         //
         verifyException("org.telegram.telegrambots.updatesreceivers.DefaultBotSession", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      defaultBotSession0.setToken("q4 AjS kc5%Mp[");
      // Undeclared exception!
      try { 
        defaultBotSession0.setToken("z|8<vtpc]iAGi i");
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // Token has already been set
         //
         verifyException("org.telegram.telegrambots.updatesreceivers.DefaultBotSession", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      FakeLongPollingBot fakeLongPollingBot0 = new FakeLongPollingBot();
      BotOptions botOptions0 = fakeLongPollingBot0.getOptions();
      defaultBotSession0.setOptions(botOptions0);
      // Undeclared exception!
      try { 
        defaultBotSession0.setOptions(botOptions0);
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // BotOptions has already been set
         //
         verifyException("org.telegram.telegrambots.updatesreceivers.DefaultBotSession", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      // Undeclared exception!
      try { 
        defaultBotSession0.stop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Session already stopped
         //
         verifyException("org.telegram.telegrambots.updatesreceivers.DefaultBotSession", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      DefaultBotSession.UpdatesSupplier defaultBotSession_UpdatesSupplier0 = mock(DefaultBotSession.UpdatesSupplier.class, new ViolatedAssumptionAnswer());
      defaultBotSession0.setUpdatesSupplier(defaultBotSession_UpdatesSupplier0);
      assertFalse(defaultBotSession0.isRunning());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      boolean boolean0 = defaultBotSession0.isRunning();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DefaultBotSession defaultBotSession0 = new DefaultBotSession();
      // Undeclared exception!
      try { 
        defaultBotSession0.start();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.updatesreceivers.DefaultBotSession", e);
      }
  }
}
