/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 19:00:46 GMT 2018
 */

package org.telegram.telegrambots.session;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.Serializable;
import org.apache.shiro.session.Session;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.session.DefaultChatIdConverter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultChatIdConverter_ESTest extends DefaultChatIdConverter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultChatIdConverter defaultChatIdConverter0 = new DefaultChatIdConverter(0L);
      // Undeclared exception!
      try { 
        defaultChatIdConverter0.setSessionId((Serializable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.session.DefaultChatIdConverter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultChatIdConverter defaultChatIdConverter0 = new DefaultChatIdConverter();
      // Undeclared exception!
      try { 
        defaultChatIdConverter0.setSessionId("org.apache.shiro.ShiroException");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Long
         //
         verifyException("org.telegram.telegrambots.session.DefaultChatIdConverter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultChatIdConverter defaultChatIdConverter0 = new DefaultChatIdConverter();
      Serializable serializable0 = defaultChatIdConverter0.getSessionId();
      assertEquals(0L, serializable0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultChatIdConverter defaultChatIdConverter0 = new DefaultChatIdConverter((-4500L));
      Serializable serializable0 = defaultChatIdConverter0.generateId((Session) null);
      defaultChatIdConverter0.setSessionId(serializable0);
  }
}
