/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 19:00:47 GMT 2018
 */

package org.telegram.telegrambots.session;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.Serializable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.telegram.telegrambots.session.DefaultChatSessionContext;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultChatSessionContext_ESTest extends DefaultChatSessionContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultChatSessionContext defaultChatSessionContext0 = new DefaultChatSessionContext(1698L, (String) null);
      String string0 = defaultChatSessionContext0.getHost();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultChatSessionContext defaultChatSessionContext0 = new DefaultChatSessionContext(1698L, (String) null);
      defaultChatSessionContext0.setHost("");
      String string0 = defaultChatSessionContext0.getHost();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultChatSessionContext defaultChatSessionContext0 = new DefaultChatSessionContext(1698L, (String) null);
      // Undeclared exception!
      try { 
        defaultChatSessionContext0.setSessionId((Serializable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.telegrambots.session.DefaultChatSessionContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultChatSessionContext defaultChatSessionContext0 = new DefaultChatSessionContext((-2432L), "");
      // Undeclared exception!
      try { 
        defaultChatSessionContext0.setSessionId("");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Long
         //
         verifyException("org.telegram.telegrambots.session.DefaultChatSessionContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultChatSessionContext defaultChatSessionContext0 = new DefaultChatSessionContext((-13L), "d");
      Serializable serializable0 = defaultChatSessionContext0.getSessionId();
      defaultChatSessionContext0.setSessionId(serializable0);
      assertEquals(0, defaultChatSessionContext0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DefaultChatSessionContext defaultChatSessionContext0 = new DefaultChatSessionContext((-13L), "d");
      String string0 = defaultChatSessionContext0.getHost();
      assertEquals("d", string0);
  }
}
