/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 22 18:50:24 GMT 2018
 */

package org.telegram.abilitybots.api.sender;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.telegram.abilitybots.api.sender.MessageSender;
import org.telegram.abilitybots.api.sender.SilentSender;
import org.telegram.telegrambots.meta.api.methods.BotApiMethod;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SilentSender_ESTest extends SilentSender_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SilentSender silentSender0 = new SilentSender((MessageSender) null);
      // Undeclared exception!
      try { 
        silentSender0.sendMd("Could not execute bot API method", 3635L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.abilitybots.api.sender.SilentSender", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SilentSender silentSender0 = new SilentSender((MessageSender) null);
      // Undeclared exception!
      try { 
        silentSender0.send("", 1096L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.abilitybots.api.sender.SilentSender", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SilentSender silentSender0 = new SilentSender((MessageSender) null);
      // Undeclared exception!
      try { 
        silentSender0.forceReply("8(jxC?\"M/Q0e`", 0L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.abilitybots.api.sender.SilentSender", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SilentSender silentSender0 = new SilentSender((MessageSender) null);
      BotApiMethod<String> botApiMethod0 = (BotApiMethod<String>) mock(BotApiMethod.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        silentSender0.executeAsync(botApiMethod0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.abilitybots.api.sender.SilentSender", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SilentSender silentSender0 = new SilentSender((MessageSender) null);
      BotApiMethod<String> botApiMethod0 = (BotApiMethod<String>) mock(BotApiMethod.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        silentSender0.execute(botApiMethod0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.telegram.abilitybots.api.sender.SilentSender", e);
      }
  }
}
